Added Messages

diff --git a/usr/local/sbin/eemigrate b/usr/local/sbin/eemigrate
--- a/usr/local/sbin/eemigrate
+++ b/usr/local/sbin/eemigrate
@@ -87,7 +87,7 @@ EEMIGEXCLUDE()
 {
 	echo
 	echo -e " IMPORTANT: "
-	read -p " List of Files or Folder to be Exclude, Seperate by Space: " EEMIGEXCLUDEINPUT
+	read -p " List of Files or Folder to be Exclude (Seperate by Space): " EEMIGEXCLUDEINPUT
 
 	for i in $EEMIGEXCLUDEINPUT
 	do
@@ -105,19 +105,16 @@ EEMIGLOCALDB()
 	# Check If wp-config.php file exist or not
 	if [[ -f $MIGSRCCONFIG ]]
 	then
+
+		# MySQL Informatiom from wp-config.php file
+		MIGSRCDBNAME=$(grep DB_NAME $MIGSRCCONFIG | cut -d"'" -f4)
+		MIGSRCDBUSER=$(grep DB_USER $MIGSRCCONFIG | cut -d"'" -f4)
+		MIGSRCDBPASS=$(grep DB_PASS $MIGSRCCONFIG | cut -d"'" -f4)
+
 		MIGDBEXPORT=y
-	elif [[ -f /var/www/$MIGLOCALDOMAIN/htdocs/wp-config.php ]]
-	then
-		MIGDBEXPORT=y
-		MIGSRCCONFIG=/var/www/$MIGLOCALDOMAIN/htdocs/wp-config.php
 	else
 		MIGDBEXPORT=n
 	fi
-
-	# MySQL Informatiom from wp-config.php file
-	MIGSRCDBNAME=$(grep DB_NAME $MIGSRCCONFIG | cut -d"'" -f4)
-	MIGSRCDBUSER=$(grep DB_USER $MIGSRCCONFIG | cut -d"'" -f4)
-	MIGSRCDBPASS=$(grep DB_PASS $MIGSRCCONFIG | cut -d"'" -f4)
 } # End of EEMIGLOCALDB
 
 
@@ -127,8 +124,10 @@ EEMIGREMOTEDB()
 	# Remove old wp-config.php from /tmp/ directory
 	rm -rf /tmp/wp-config.php
 
+	echo -e "\033[34mRequired Database Details from Remote Server\e[0m"
+
 	# Get Remote wp-config.php file path in MIGDESTCONFIG
-	rsync -dmavzh $MIGREMOTEUSER@$MIGREMOTEIP:/var/www/$MIGREMOTEDOMAIN/{wp-config.php,htdocs/wp-config.php} /tmp/
+	rsync -dmavzh $MIGREMOTEUSER@$MIGREMOTEIP:/var/www/$MIGREMOTEDOMAIN/wp-config.php /tmp/
 
 	# Rename wp-config file name to avoid conflict
 	mv /tmp/wp-config.php /tmp/$MIGREMOTEDOMAIN-wp-config.php
@@ -138,29 +137,33 @@ EEMIGREMOTEDB()
 	# Check If wp-config.php file exist or not
 	if [[ -f $MIGDESTCONFIG ]]
 	then
+
+		# MySQL Informatiom from wp-config.php file
+		MIGDESTDBNAME=$(grep DB_NAME $MIGDESTCONFIG | cut -d"'" -f4)
+		MIGDESTDBUSER=$(grep DB_USER $MIGDESTCONFIG | cut -d"'" -f4)
+		MIGDESTDBPASS=$(grep DB_PASS $MIGDESTCONFIG | cut -d"'" -f4)
+
 		MIGDBEXPORT=y
 	else
 		MIGDBEXPORT=n
 	fi
-
-	# MySQL Informatiom from wp-config.php file
-	MIGDESTDBNAME=$(grep DB_NAME $MIGDESTCONFIG | cut -d"'" -f4)
-	MIGDESTDBUSER=$(grep DB_USER $MIGDESTCONFIG | cut -d"'" -f4)
-	MIGDESTDBPASS=$(grep DB_PASS $MIGDESTCONFIG | cut -d"'" -f4)
 } # End of EEMIGREMOTEDB
 
 
 # MySQL Export Function
 EEMIGMYSQLEXPORT()
 {
-	echo -e "\033[34m \n Taking MySQL Dump, Please Wait... \n \e[0m"
-
+	# Export MySQL
 	if [[ "$EEMIGMETHOD" == "push" ]]
 	then
+		echo -e "\033[34m \n Taking MySQL Dump, Please Wait... \n \e[0m"
 		mysqldump --max_allowed_packet=512M -u $MIGSRCDBUSER -p$MIGSRCDBPASS $MIGSRCDBNAME > /var/www/$MIGLOCALDOMAIN/$MIGSRCDBNAME.sql || SyncError "Unable To Dump MySQL For $MIGSRCDBNAME"
 	elif [[ "$EEMIGMETHOD" == "pull" ]]
 	then
+		echo -e "\033[34m \n Taking MySQL Dump from Remote Server \n \e[0m"
 		ssh $MIGREMOTEUSER@$MIGREMOTEIP -p $MIGREMOTEPORT "mysqldump --max_allowed_packet=512M -u $MIGDESTDBUSER -p$MIGDESTDBPASS $MIGDESTDBNAME > /var/www/$MIGREMOTEDOMAIN/$MIGDESTDBNAME.sql" || SyncError "Unable To Dump MySQL For $MIGDESTDBNAME"
+
+		echo -e "\033[34m \n Sync $MIGDESTDBNAME.sql to /var/www/$MIGLOCALDOMAIN/ \n \e[0m"
 		rsync -dmavzh  $MIGREMOTEUSER@$MIGREMOTEIP:/var/www/$MIGREMOTEDOMAIN/$MIGDESTDBNAME.sql /var/www/$MIGLOCALDOMAIN/ || SyncError "Unable To Fetch $MIGDESTDBNAME.sql From $MIGREMOTEDOMAIN"
 	fi
 } # End of EEMIGMYSQLEXPORT
@@ -170,42 +173,20 @@ EEMIGMYSQLEXPORT()
 EEMIGMYSQLIMPORT()
 {
 	# Import MySQL to Destination
-	echo -e "\033[34m \n Importing MySQL, Please Wait... \n \e[0m"
 
 	if [[ "$EEMIGMETHOD" == "push" ]]
 	then
+		echo -e "\033[34m \n Sending Database to Remote Server, Please Wait... \n \e[0m"
 		rsync -dmavzh  /var/www/$MIGLOCALDOMAIN/$MIGSRCDBNAME.sql $MIGREMOTEUSER@$MIGREMOTEIP:/var/www/$MIGREMOTEDOMAIN/ || SyncError "Unable To Send $MIGSRCDBNAME to $MIGREMOTEDOMAIN"
+
+		echo -e "\033[34m \n Importing Database to Remote Server, Please Wait... \n \e[0m"
 		ssh $MIGREMOTEUSER@$MIGREMOTEIP -p $MIGREMOTEPORT "mysql -u $MIGDESTDBUSER -p$MIGDESTDBPASS $MIGDESTDBNAME < /var/www/$MIGREMOTEDOMAIN/$MIGSRCDBNAME.sql" || SyncError "Unable To Import MySQL On $MIGREMOTEDOMAIN"
 	elif [[ "$EEMIGMETHOD" == "pull" ]]
 	then
+		echo -e "\033[34m \n Importing Database, Please Wait... \n \e[0m"
 		mysql -u $MIGSRCDBUSER -p$MIGSRCDBPASS $MIGSRCDBNAME < /var/www/$MIGLOCALDOMAIN/$MIGDESTDBNAME.sql || SyncError "Unable To Import $MIGDESTDBNAME.sql On $MIGLOCALDOMAIN"
 	fi
 } # End of EEMIGMYSQLIMPORT
-
-
-# Add WP_HOME and WP_SITEURL to wp-config.php file
-EEMIGUPDATECONFIG()
-{
-	if [[ "$EEMIGMETHOD" == "push" ]]
-	then
-
-		if ! grep -w -q WP_HOME $MIGDESTCONFIG && ! grep -w -q WP_SITEURL $MIGDESTCONFIG
-		then
-			ssh $MIGREMOTEUSER@$MIGREMOTEIP -p $MIGREMOTEPORT "echo \"\ndefine( 'WP_HOME', 'http://$MIGREMOTEDOMAIN' ); \ndefine( 'WP_SITEURL', 'http://$MIGREMOTEDOMAIN' ); \" >> /var/www/$MIGREMOTEDOMAIN/wp-config.php" || SyncError "Unable To Add WP_HOME and WP_SITEURL in /var/www/$MIGREMOTEDOMAIN/wp-config.php"
-			echo -e "Added WP_HOME and WP_SITEURL to /var/www/$MIGREMOTEDOMAIN/wp-config.php"
-		fi
-
-	elif [[ "$EEMIGMETHOD" == "pull" ]]
-	then
-
-		if ! grep -w -q WP_HOME $MIGSRCCONFIG && ! grep -w -q WP_SITEURL $MIGSRCCONFIG
-		then
-			echo -e "\ndefine( 'WP_HOME', 'http://$MIGLOCALDOMAIN' ); \ndefine( 'WP_SITEURL', 'http://$MIGLOCALDOMAIN' );" >> /var/www/$MIGLOCALDOMAIN/wp-config.php || SyncError "Unable To Add WP_HOME and WP_SITEURL in /var/www/$MIGLOCALDOMAIN/wp-config.php"
-			echo -e "Added WP_HOME and WP_SITEURL to /var/www/$MIGLOCALDOMAIN/wp-config.php"
-		fi
-
-	fi
-} # End of EEMIGUPDATECONFIG
 
 
 # Database Processing
@@ -214,9 +195,6 @@ EEMIGDBPROCESS()
 	# Export and Import Database if wp-config file present
 	if [[ "$MIGDBEXPORT" == "y" ]]
 	then
-
-		# Export MySQL
-		EEMIGMYSQLEXPORT
 
 		# Ask for Import Database from Source to Destination
 		if [[ "$EEMIGMETHOD" == "push" ]]
@@ -235,6 +213,9 @@ EEMIGDBPROCESS()
 
 		if [[ "$EEMIGDBIMPORT" == "y" ]]
 		then
+			# Export MySQL
+			EEMIGMYSQLEXPORT
+
 			# Import MySQL
 			EEMIGMYSQLIMPORT
 		else
@@ -243,6 +224,31 @@ EEMIGDBPROCESS()
 
 	fi
 } # End of EEMIGDBPROCESS
+
+
+# Add WP_HOME and WP_SITEURL to wp-config.php file
+EEMIGUPDATECONFIG()
+{
+	if [[ "$EEMIGMETHOD" == "push" ]]
+	then
+
+		if ! grep -w -q WP_HOME $MIGDESTCONFIG && ! grep -w -q WP_SITEURL $MIGDESTCONFIG
+		then
+			echo -e "Adding WP_HOME and WP_SITEURL Details to /var/www/$MIGREMOTEDOMAIN/wp-config.php"
+			ssh $MIGREMOTEUSER@$MIGREMOTEIP -p $MIGREMOTEPORT "echo -e \"\ndefine( 'WP_HOME', 'http://$MIGREMOTEDOMAIN' ); \ndefine( 'WP_SITEURL', 'http://$MIGREMOTEDOMAIN' ); \" >> /var/www/$MIGREMOTEDOMAIN/wp-config.php" || SyncError "Unable To Add WP_HOME and WP_SITEURL in /var/www/$MIGREMOTEDOMAIN/wp-config.php"
+		fi
+
+	elif [[ "$EEMIGMETHOD" == "pull" ]]
+	then
+
+		if ! grep -w -q WP_HOME $MIGSRCCONFIG && ! grep -w -q WP_SITEURL $MIGSRCCONFIG
+		then
+			echo -e "Adding WP_HOME and WP_SITEURL Details to /var/www/$MIGLOCALDOMAIN/wp-config.php"
+			echo -e "\ndefine( 'WP_HOME', 'http://$MIGLOCALDOMAIN' ); \ndefine( 'WP_SITEURL', 'http://$MIGLOCALDOMAIN' );" >> /var/www/$MIGLOCALDOMAIN/wp-config.php || SyncError "Unable To Add WP_HOME and WP_SITEURL in /var/www/$MIGLOCALDOMAIN/wp-config.php"
+		fi
+
+	fi
+} # End of EEMIGUPDATECONFIG
 
 
 # Webroot Migration
